### ISSUE TITLE
Add timestamps to logging functions

### ISSUE THREAD

**Issue by jlashner** [slaclab/rogue#1011]
I am looking throug failure logs for Simons Observatory's SMuRF software, and am finding that it would be really nice to have timestamps on more log messages. For instance, here is a sample of the logs from an old run:
```
ERROR:pyrogue.Variable.RemoteVariable.AMCc.FpgaTopLevel.AppTop.AppCore.SysgenCryo.Base[7].CryoChannels.etaI[28]:int too big to convert
Traceback (most recent call last):
  File "/usr/local/src/rogue/python/pyrogue/_Variable.py", line 324, in set
    self._block.set(self, value)
  File "/usr/local/src/rogue/python/pyrogue/_Block.py", line 362, in set
    ba = var._base.toBytes(value)
  File "/usr/local/src/rogue/python/pyrogue/_Model.py", line 128, in toBytes
    ba = value.to_bytes(byteCount(self.bitSize), self.endianness, signed=True)
OverflowError: int too big to convert
ERROR:pyrogue.Variable.RemoteVariable.AMCc.FpgaTopLevel.AppTop.AppCore.SysgenCryo.Base[7].CryoChannels.etaI[28]:Error setting value '-50008' to variable 'AMCc.FpgaTopLevel.AppTop.AppCore.SysgenCryo.          Base[7].CryoChannels.etaI[28]' with type Int16. Exception=int too big to convert
1718215269.675174:pyrogue.epicsV3.Value: Error setting value from epics: smurf_server_s7:AMCc:FpgaTopLevel:AppTop:AppCore:SysgenCryo:Base[7]:CryoChannels:etaMagArray

/tmp/fw/rogue_MicrowaveMuxBpEthGen2_v1.1.0.zip/python/CryoDet/DspCoreLib/CryoDetCmbHcd/_SerialEtaScan.py:88: RuntimeWarning: divide by zero encountered in scalar divide
ERROR:pyrogue.PollQueue:'Memory Error for AMCc.FpgaTopLevel.AppTop.DaqMuxV2[1].DbgInputValid at address 0xb000002c Timeout waiting for register transaction message response'
ERROR:pyrogue.PollQueue:'Memory Error for AMCc.FpgaTopLevel.AmcCarrierCore.SwRssiServer[1].RetransmitCnt at address 0xa01104c Timeout waiting for register transaction message response'
ERROR:pyrogue.PollQueue:'Memory Error for AMCc.FpgaTopLevel.AppTop.DaqMuxV2[1].TriggerSwStatus at address 0xb0000004 Timeout waiting for register transaction message response'
ERROR:pyrogue.PollQueue:'Memory Error for AMCc.FpgaTopLevel.AmcCarrierCore.EM22xx.READ_TEMPERATURE_1 at address 0xd000234 Timeout waiting for register transaction message response'
ERROR:pyrogue.PollQueue:'Memory Error for AMCc.FpgaTopLevel.AmcCarrierCore.AxiVersion.UpTimeCnt at address 0x000008 Timeout waiting for register transaction message response'
ERROR:pyrogue.PollQueue:'Memory Error for AMCc.FpgaTopLevel.AppTop.AppTopJesd[0].JesdRx.RawData[5] at address 0xc0000154 Timeout waiting for register transaction message response'
```
There are some timestamps here, but the `Timeout waiting for register transaction message response` errors have none. Can we add timestamps to all rogue log messages?

**Comment by slacrherbst** [comment]
There are two logging mechanisms in use in Rogue. The lower level logging is a custom library in C++ and this is the one which includes the timestamps in the dump above.

The second is at the python level which uses the standard python logging package. By default in this library messages with a log level of warning or higher are printed with the standard formatting.

To add timestamps you need to configure the logging settings in the top level python file. An example configuration which achieives this is:

logging.basicConfig(
    format='%(asctime)s %(levelname)-8s %(message)s',
    #level=logging.INFO,
    datefmt='%Y-%m-%d %H:%M:%S')

Here you can also change the default log level in this command. To achieve this the above should be added at this location in the pysmurf package:

https://github.com/slaclab/pysmurf/blob/1ff66325bf174f975c241b5cf6922f378dd58b20/server_scripts/cmb_eth.py#L27
